Feature/synchronize
alibaba/FederatedScope pull request #3
Opened 2022-04-03 06:03 UTC by xieyxclack

To synchronize the code with our gitlab

2022-04-03 06:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/FederatedScope?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/FederatedScope?pullRequest=3) before we can accept your contribution.<br/><hr/>**yuexiang.xyx** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/FederatedScope?pullRequest=3) it.</sub>

2022-04-06 02:28 UTC, joneswong commented on federatedscope/attack/example_attack_config/reconstruct_IG_fedavg_opt_on_femnist.yaml
> +<<<<<<< HEAD
both modified

2022-04-06 02:28 UTC, joneswong commented on federatedscope/attack/example_attack_config/reconstruct_fedavg_opt_on_femnist.yaml
> +<<<<<<< HEAD
both modified

2022-04-06 02:31 UTC, joneswong requested changes
It seems that there are still several conflicts.

2022-04-06 02:39 UTC, xieyxclack commented
> It seems that there are still several conflicts.

I have resolved the conflicts accordingly.

2022-04-06 02:49 UTC, rayrayraykk commented
How about remove `docker_file/feratedscope_jupyterhub`?

2022-04-06 06:01 UTC, joneswong approved these changes
Approve!

2022-04-06 06:02 UTC, merged